### ISSUE TITLE
What we pass into gulp.src()

### ISSUE THREAD

**Issue by benrich** [rbalicki2/gulp-json-sass#2]
According to the gulp.src() documentation it can accept either a string or an array.  The example though in gulp-json-sass isn't really doing either.  Would one agree?

.src('example.json', 'example.sass')

This gives me this error: TypeError: Arguments to path.resolve must be strings

Should it not be .src(['example.json', 'example.sass']) ?

When I do this src doesn't error and the gulp task competes.  Although my gulp.dest() file is empty (so it didn't work).

Any ideas or discussion?

Thanks!

**Comment by rbalicki2** [comment]
Thank you! Good catch. You are right, and I fixed the readme.
If you copy-paste your gulpfile, I can take a look at your pipeline and suggest a fix. (I suspect that only example.json is being passed to your sass compiler. The resulting sass contains no selectors, so it will render as an empty file.)

**Comment by benrich** [comment]
Yep that's what was going on.  I've sorted it now fortunately.  Cheers dude
