### ISSUE TITLE
Type Error: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by mdatelle** [rbalicki2/gulp-json-sass#3]
Getting a Type Error when trying to run the jsonSass task. I'm using Gulp version 3.8.11. Here's my gulpfile.js code and package.json. I'm wondering if the changes to gulp-ruby-sass mentioned in the below Stackoverflow article have something to do with this error. Thanks for your help with this!

http://stackoverflow.com/questions/28140012/gulp-typeerror-arguments-to-path-join-must-be-strings

// package.json

{
  "devDependencies": {
    "gulp": "~3.8.11",
    "gulp-rename": "~1.2.0",
    "gulp-ruby-sass": "~0.0.2",
    "gulp-concat": "~2.5.2",
    "gulp-cache": "~0.2.8",
    "gulp-notify": "~2.2.0",
    "gulp-minify-css": "~0.5.1",
    "gulp-uglify": "~1.1.0",
    "gulp-jshint": "~1.9.2",
    "gulp-autoprefixer": "~2.1.0"
  },
  "dependencies": {
    "gulp-json-sass": "0.0.2"
  }
}

// gulpfile.js

gulp.task('json-sass', function () {
    return gulp.src(['themes/tydb/sass/vars/json/colors.json', 'themes/tydb/sass/vars/json-colors.scss'])
        .pipe(jsonSass({
            sass: false
        }))
        .pipe(concat('themes/tydb/sass/vars/colors.scss'))
        .pipe(sass())
        .pipe(gulp.dest('themes/tydb/sass/vars'));
});

// colors.json (This is the json I'm trying to convert to scss.)

{
  "primaryColor1": "#eef4f4",
  "primaryColor2": "#e2f3f4",
  "primaryColor3": "#dfeced",
  "primaryColor4": "#a3d3d7",
  "primaryColor5": "#cae1e3",
  "primaryColor6": "#66bac0",
  "primaryColor7": "#2c8db9",
  "primaryColor8": "#18919a",
  "primaryColor9": "#075b61",
  "primaryColor10": "#3b8a8f",
  "secondaryColor1": "#eff6f7",
  "secondaryColor2": "#d9e8ed",
  "secondaryColor3": "#dfeced",
  "secondaryColor4": "#deeced",
  "secondaryColor5": "#b2d9de",
  "secondaryColor6": "#95c0d1",
  "secondaryColor7": "#46aacd",
  "secondaryColor8": "#2c8db9",
  "secondaryColor9": "#31639a",
  "tertiaryColor1": "#f7f7f7",
  "tertiaryColor2": "#eeeeee",
  "tertiaryColor3": "#e0e0e0",
  "tertiaryColor4": "#cccccc",
  "tertiaryColor5": "#dddddd",
  "tertiaryColor6": "#999999",
  "tertiaryColor7": "#666666",
  "tertiaryColor8": "#333333",
  "tertiaryColor9": "#f2f2f2",
  "tertiaryColor10": "#aaaaaa",
  "tertiaryColor11": "#474747",
  "tertiaryColor12": "#efefef",
  "tertiaryColor13": "#555555",
  "tertiaryColor14": "#e6e6e6",
  "tertiaryColor15": "#626262",
  "tertiaryColor16": "#a3d3d7",
  "tertiaryColor17": "#dfeced",
  "negative2": "#d18e8e",
  "negative3": "#d15050",
  "negative4": "#d04141",
  "positive3": "#b4d781",
  "positive4": "#9bbe68",
  "additionalColor1": "#d6cddd",
  "additionalColor2": "#cae1e3",
  "additionalColor3": "#b2bfc0",
  "additionalColor4": "#f7941d",
  "additionalColor5": "#e18719",
  "additionalColor6": "#f1d90b",
  "colorWhite1": "#ffffff",
  "colorBlack": "#000000",
  "boxBorder": "#c1e3e5",
  "transparentColor": "rgba(0,0,0,0)",
  "tableColor": "#e9ecef"
}

**Comment by rbalicki2** [comment]
Looks like those syntax changes only apply to version 1+ of gulp-json-sass,
so it's probably not that. I'll look into it, though, and see what I find.

**Comment by rbalicki2** [comment]
mdatelle - hope you found this package useful!
Could you post a stack trace of the error? I can't seem to recreate it. I have no problems compiling colors.json into scss and importing it into another file.
