### ISSUE TITLE
way to include quoted text in the output?

### ISSUE THREAD

**Issue by thisispete** [rbalicki2/gulp-json-sass#4]
Say my JSON is used for other things and I happen to have some formatted text included, that I don't need to use as a style; like: 
```
{
  "someObject":{
    "color": "#FFFFFF",
    "copy": "This is some text. It isn't used as a style."
  }
}
```
and I do 
```
var jsonSass = require('json-sass');
jsonSass({
   prefix: '$wrapper: ',
});
```
the converted sass output is
```
$wrapper: {
  someObject: {
    color: #FFFFFF,
    copy: This is some text. It isn't used as a style.
  }
}
```
so far so good, except if I include that file in another sass file to consume it as variables it throws errors on compilation on the line for copy:

>error reading values after text

so I guess I was wondering is there a way to maintain the quotes? 
I tried the `escapeIllegalCharacters` flag... Any other ideas?

**Comment by rbalicki2** [comment]
Looks like you're using the json-sass library and not mine :-D
That being said, I can't seem to recreate this. I can import that sass file into another with no issue. (FWIW I'm using the SCSS syntax, perhaps it is more forgiving.)

Good luck!
