### ISSUE TITLE
SASS Maps?

### ISSUE THREAD

**Issue by drolsen** [rbalicki2/gulp-json-sass#5]
I've noticed there is no option to build SASS variable maps?
http://www.sitepoint.com/using-sass-maps/

**Comment by pete-hotchkiss** [comment]
might be a touch late for you Devin, but I'm working on an update to this which will parse more complex object types.

Currently only got arrays parsing to lists, but maps are on my to-do list

https://github.com/pete-hotchkiss/gulp-sass-external-variables

**Comment by rbalicki2** [comment]
@pete-hotchkiss Thank you!
